### ISSUE TITLE
Another repo of Buzz machines sources

### ISSUE THREAD

**Issue by Gimmeapill** [remithomas/jeskola_buzz#1]
Hi Remi,

I just found your repo while browsing GitHub, & I just wanted to bring to your attention this collection of old Buzz machines sources by the authors of Buze & Buzztrax: 
https://github.com/Buzztrax/buzzmachines
If you're already aware please ignore ;-)

BR,

LX

**Comment by remithomas** [comment]
Hi,
no I didn't know about this repo, I just starred it.
Thanks

Rémi
